// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Ambient_Sound___Howling_wind = "Ambient Sound - Howling wind",
  Ambient_Sound___Market = "Ambient Sound - Market",
  Ambient_Sound___footsteps = "Ambient Sound - footsteps",
  Grave_04 = "Grave 04",
  Grave_04_2 = "Grave 04_2",
  Grave_04_3 = "Grave 04_3",
  Grave_04_5 = "Grave 04_5",
  Grave_15 = "Grave 15",
  Grave_15_2 = "Grave 15_2",
  Grave_15_3 = "Grave 15_3",
  Grave_31 = "Grave 31",
  Grave_31_2 = "Grave 31_2",
  Grave_31_3 = "Grave 31_3",
  Grave_31_4 = "Grave 31_4",
  Iron_Fence = "Iron Fence",
  Iron_Fence_4 = "Iron Fence 4",
  Iron_Fence_4_11 = "Iron Fence 4_11",
  Iron_Fence_4_2_3 = "Iron Fence 4_2_3",
  Iron_Fence_4_2_3_4_5 = "Iron Fence 4_2_3_4_5",
  Iron_Fence_4_2_3_4_5_6 = "Iron Fence 4_2_3_4_5_6",
  Iron_Fence_4_2_3_4_5_6_7 = "Iron Fence 4_2_3_4_5_6_7",
  Iron_Fence_4_2_3_5 = "Iron Fence 4_2_3_5",
  Iron_Fence_4_2_3_6 = "Iron Fence 4_2_3_6",
  Iron_Fence_4_2_3_7 = "Iron Fence 4_2_3_7",
  Iron_Fence_4_2_4 = "Iron Fence 4_2_4",
  Iron_Fence_4_2_4_5 = "Iron Fence 4_2_4_5",
  Iron_Fence_4_2_4_5_6 = "Iron Fence 4_2_4_5_6",
  Iron_Fence_4_2_5 = "Iron Fence 4_2_5",
  Iron_Fence_4_3 = "Iron Fence 4_3",
  Iron_Fence_4_3_4 = "Iron Fence 4_3_4",
  Iron_Fence_4_3_4_5 = "Iron Fence 4_3_4_5",
  Iron_Fence_4_3_4_5_6 = "Iron Fence 4_3_4_5_6",
  Iron_Fence_4_3_4_6 = "Iron Fence 4_3_4_6",
  Iron_Fence_4_3_4_7 = "Iron Fence 4_3_4_7",
  Iron_Fence_4_3_5 = "Iron Fence 4_3_5",
  Iron_Fence_4_3_6 = "Iron Fence 4_3_6",
  Iron_Fence_4_4 = "Iron Fence 4_4",
  Iron_Fence_4_5 = "Iron Fence 4_5",
  Iron_Fences = "Iron Fences",
  Iron_Fences_2 = "Iron Fences_2",
  KILLERHOUSE__glb = "KILLERHOUSE_.glb",
  Long_Opened_Wooden_Crate = "Long Opened Wooden Crate",
  Old_Wooden_Door = "Old Wooden Door",
  Old_Wooden_Door_2 = "Old Wooden Door_2",
  Skull = "Skull",
  Soccer_Ball_3 = "Soccer Ball_3",
  Vertical_Red_Pad = "Vertical Red Pad",
  blade_glb = "blade.glb",
  blade_glb_2 = "blade.glb_2",
  butchersknife = "butchersknife",
  carpet = "carpet",
  carpet_2 = "carpet_2",
  carpet_3 = "carpet_3",
  fplank_glb = "fplank.glb",
  fplank_glb_2 = "fplank.glb_2",
  fplank_glb_3 = "fplank.glb_3",
  fplank_glb_4 = "fplank.glb_4",
  oldtable = "oldtable",
  pilar = "pilar",
  pilar_glb_2 = "pilar.glb_2",
  pilar_glb_3 = "pilar.glb_3",
  pilar_glb_4 = "pilar.glb_4",
  pilar_glb_5 = "pilar.glb_5",
  pilar_glb_6 = "pilar.glb_6",
  pilar_glb_7 = "pilar.glb_7",
  pilar_glb_8 = "pilar.glb_8",
  pilars = "pilars",
  wallshelf = "wallshelf",
} 
